version: '3.8'

services:
  app:
    image: adamboutcher/statping-ng
    container_name: statping-ng
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
    volumes:
      - ./data/statpingNG:/app
      - ./data/statpingNG/asset:/app/assets