version: '3.8'

services:
  app:
    image: adamboutcher/statping-ng
    container_name: statping-ng
    ports:
      - "8090:8090"
    # stdin_open: true
    # tty: true
    restart: always
    volumes:
      - ./data/statping-new:/app
      # - ./data/statping/asset:/app/assets